### ISSUE TITLE
Benchmark new listing optimization on QA satellite

### ISSUE THREAD

**Issue by mniewrzal** [storj/team-metainfo#122]
We need to benchmark optimization done with https://github.com/storj/storj/issues/5088

First we have to get the feature flag set to true on the QA satellite.

We need to check two things: 
- check the performance of non-recursive listing
- check the impact on recursive listing.

We could have 4 scenario:
- 1 object in one bucket (most common case - shouldn't see an impact)
- 1000 objects in 1 bucket
- 1000 prefixes in 1 bucket (with one object)
- 10 prefixes with 100 objects each.

For each of these scenarios, we should compare runs of listing the bucket recursively and non-recursively and with/wthout system infos and metadata.

We should compare both the impact:
- on the satellite, 
- from uplink
- in cockroachdb (query execution time + bytes exchanged).

**Comment by iglesiasbrandon** [comment]
Hey, @mniewrzal I don't think this issue is relevant anymore I'm going to close it. Please reopen the issue if it is.
