### ISSUE TITLE
Use single call to get project upload limits

### ISSUE THREAD

**Issue by mniewrzal** [storj/team-metainfo#124]
Currently, checking upload limits (`ExceedsUploadLimits`) we are separately getting storage and segment limit from cache. We should be able to replace those two calls with single `GetProjectLimits` which returns all project limits (bandwidth, storage, segment). Code will be cleaner and method will execute slightly faster.

Acceptance Criteria:
* update `ExceedsUploadLimits` to use `GetProjectLimits` instead `GetProjectSegmentLimit` and `GetProjectStorageLimit` separately
* remove `ProjectLimitCache.GetProjectSegmentLimit` if its used only in `ExceedsUploadLimits`
* check if we can also remove `ProjectLimitCache.GetProjectStorageLimit` if its not used in different places and remove it if possible

**Comment by Qweder93** [comment]
https://review.dev.storj.io/c/storj/storj/+/8411
