### ISSUE TITLE
Add missing methods to metainfo.Batch

### ISSUE THREAD

**Issue by mniewrzal** [storj/team-metainfo#94]
For sure we are missing:
* BeginMoveObject
* FinishMoveObject
* DownloadObject
* BeginCopyObject
* FinishCopyObject
* GetObjectIP
* ListPendingObjectStreams

**Comment by Fadila82** [comment]
For each request, we need to: 
- add its handling in here: https://github.com/storj/storj/blob/e3ac0ae2c29f1682ca01002afe2ef5c158ed78cc/satellite/metainfo/batch.go#L30 for the satellite side, 
- and here for uplink: https://github.com/storj/uplink/blob/202ea09a93c5fc7322565f375cfca3a9c6afb45c/private/metaclient/batch.go#L29

It seems they are already in metainfo protobuf: https://github.com/storj/common/blob/1cde7e384e77f8528f8cc389e650070dd857e92b/pb/metainfo.proto#L695

**Comment by Erikvv** [comment]
Added to arch review agenda question wether we should pre-emptively maintain this.
