### ISSUE TITLE
Prepare a presentation for Nextcloud webinar

### ISSUE THREAD

**Issue by mniewrzal** [storj/team-metainfo#97]

**Comment by shaupt131** [comment]
@mniewrzal Just curious - when is this webinar?

**Comment by mniewrzal** [comment]
heh I don't remember... @Erikvv ?

**Comment by Erikvv** [comment]
March 23th 5:00 CET

**Comment by Erikvv** [comment]
Slides https://docs.google.com/presentation/d/1uLMZURvMlWQNY-o8ol7oCyv8Dl9nWH1o1yj6YjpkBX0/edit#slide=id.g1183632ac61_0_569

Demo https://link.us1.storjshare.io/s/jvakv4ddjeprfyi6iqcbrgxy5nda/public/nextcloud-storj-demo.mkv?wrap=1 (I was in a hurry. Got some feedback on this I will try to find time to record a better one)
