### ISSUE TITLE
Move tickets from Storage Node board to Metainfo board

### ISSUE THREAD

**Issue by mniewrzal** [storj/team-metainfo#99]
We have old board just for storage node tickets. We should move all reasonable tickets (some are just proposals) into Metainfo board. We should
* close tickets from Storage Node board that we won't work on
* move tickets from Storage Node to Metainfo board
* close Storage Node board

Storage Node board https://github.com/orgs/storj/projects/6

**Comment by shaupt131** [comment]
@profclems want me to knock this one out?

**Comment by profclems** [comment]
> @profclems want me to knock this one out?

Yeah sure, I'll get it done.

**Comment by shaupt131** [comment]
Sorry, I should have been more specific with what I was saying.  I was offering to move the tickets for you if you'd like me to.

**Comment by profclems** [comment]
> @profclems want me to knock this one out?

Uh, I missed the "me" in the sentence.

Sure, you can take that up. I will also go through them when you're done to see if some of the issues are still valid.

**Comment by shaupt131** [comment]
All tickets have been added to Metainfo project board.  Please go ahead and perform some cleanup when you have a chance and we'll close this out.
